// Code generated by "stringer -type StatusCode"; DO NOT EDIT.

package ocpi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GenericSuccessCode-1000]
}

const _StatusCode_name = "GenericSuccessCode"

var _StatusCode_index = [...]uint8{0, 18}

func (i StatusCode) String() string {
	i -= 1000
	if i >= StatusCode(len(_StatusCode_index)-1) {
		return "StatusCode(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _StatusCode_name[_StatusCode_index[i]:_StatusCode_index[i+1]]
}
