// Code generated by "stringer -type=StatusCode -linecomment"; DO NOT EDIT.

package ocpi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GenericSuccessCode-1000]
	_ = x[GenericClientError-2000]
	_ = x[GenericServerError-3000]
}

const (
	_StatusCode_name_0 = "Success"
	_StatusCode_name_1 = "Client Error"
	_StatusCode_name_2 = "Server Error"
)

func (i StatusCode) String() string {
	switch {
	case i == 1000:
		return _StatusCode_name_0
	case i == 2000:
		return _StatusCode_name_1
	case i == 3000:
		return _StatusCode_name_2
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
